a = int(input("Enter the 1 number:"))
b = int(input("Enter the 2 number:"))
c = int(input("Enter the 3 number:"))
d = int(input("Enter the 4 number:"))
e = int(input("Enter the 5 number:"))
f = int(input("Enter the 6 number:"))
g = int(input("Enter the 7 number:"))
h = int(input("Enter the 8 number:"))
i = int(input("Enter the 9 number:"))
j = int(input("Enter the 10 number:"))
m = max(a,b,c,d,e,f,g,h,i,j)
n = min(a,b,c,d,e,f,g,h,i,j)
print("The maximum number is",m)
print("The minimum numnber is",n)